# Generated by Django 3.1.3 on 2021-07-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20210102_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ltr_dir',
            field=models.BooleanField(default=False, verbose_name='الكتابة من اليسار'),
        ),
        migrations.AddField(
            model_name='problemsubmission',
            name='ltr_dir',
            field=models.BooleanField(default=False),
        ),
    ]
