# Generated by Django 3.1.3 on 2021-07-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_auto_20210725_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='publish',
        ),
    ]
