# Generated by Django 3.1.3 on 2021-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_remove_problem_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
