# Generated by Django 3.1.3 on 2021-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210808_0724'),
        ('accounts', '0008_auto_20210808_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='last_tasks_subs',
            field=models.ManyToManyField(blank=True, to='tasks.TaskProblemSubmission'),
        ),
    ]
