# Generated by Django 3.1.3 on 2021-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='task', to='tasks.TaskProblem'),
        ),
    ]
