# Generated by Django 3.1.3 on 2021-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210118_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='submited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
