# Generated by Django 4.2.14 on 2024-08-12 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0004_auto_20210818_1019"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Submissions",
        ),
    ]
