# Generated by Django 3.1.3 on 2021-01-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210101_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicesolution',
            options={'verbose_name': 'إجابة التمرين', 'verbose_name_plural': 'إجابات التمارين'},
        ),
    ]
